### ISSUE TITLE
Im just dumb. Forget this

### ISSUE THREAD

**Issue by juxty** [erikaheidi/dynacover#15]
Fatal error: Uncaught TypeError: Argument 2 passed to GDaisy\Placeholder\ImagePlaceholder::apply() must be of the type array, null given, called in /home/dynacover/dynacover/app/Command/Generate/TwitterController.php on line 49 and defined in /home/dynacover/dynacover/vendor/erikaheidi/gdaisy/src/Placeholder/ImagePlaceholder.php:35
Stack trace:
#0 /home/dynacover/dynacover/app/Command/Generate/TwitterController.php(49): GDaisy\Placeholder\ImagePlaceholder->apply(Resource id #78, NULL)
#1 /home/dynacover/dynacover/vendor/minicli/minicli/src/Command/CommandController.php(38): App\Command\Generate\TwitterController->handle()
#2 /home/dynacover/dynacover/vendor/minicli/minicli/src/App.php(159): Minicli\Command\CommandController->run(Object(Minicli\Command\CommandCall))
#3 /home/dynacover/dynacover/app/Command/Cover/UpdateController.php(15): Minicli\App->runCommand(Array)
#4 /home/dynacover/dynacover/vendor/minicli/minicli/src/Command/CommandController.php(38): App\Command\Cover\UpdateController->handle()
#5 /home/dynacover/dy in /home/dynacover/dynacover/vendor/erikaheidi/gdaisy/src/Placeholder/ImagePlaceholder.php on line 35

**Comment by PockySweet** [comment]
what was your issue? how did u fix it

**Comment by jopofe** [comment]
Hello @juxty ,
I had the same issue with Github Actions, but also with Docker approach. Could you tell us which was your problem and how did you solve it?
Many thx!
